version: "3.7"

services:
  postgresql:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: rola
      POSTGRES_DB: rola
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    networks:
      - internal
    expose:
      - "5432"

  redis:
    image: redis:5-alpine
    volumes:
      - "redis_data:/data"
    networks:
      - internal
    expose:
      - "6379"

  django:
    image: rolca/rola
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgresql
      - redis
    volumes:
      - ".:/app"
      - "django_media:/storage/media"
    env_file: docker.env
    entrypoint: ["./manage.py"]
    command: ["runserver", "0.0.0.0:8000"]
    networks:
      - internal
    expose:
      - "8000"

  frontend:
    image: rolca/frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    networks:
      - internal
    expose:
      - "80"

  nginx:
    image: rolca/nginx
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    depends_on:
      - django
      - frontend
    volumes:
      - "django_media:/storage/media"
    networks:
      - internal
    ports:
      - "8080:80"

volumes:
  postgres_data:
  redis_data:
  django_media:

networks:
  internal:
