[tox]
env_list = py312, py313, py314, docs, linters, packaging, migrations

[testenv]
package = wheel
extras = test
pass_env =
    ROLCA_*
commands = python -m pytest --cov=rolca --cov-report=xml {posargs}

[testenv:docs]
extras = docs
commands = sphinx-build -W --keep-going -b html docs {env_tmp_dir}/html

[testenv:linters]
extras = lint
commands =
    ruff check src/rolca
    flake8 src/rolca tests conftest.py
    isort --check-only --diff src/rolca tests conftest.py docs/conf.py
    black --check src/rolca tests conftest.py docs/conf.py

[testenv:packaging]
extras = package
commands =
    check-manifest
    python -m build --outdir {env_tmp_dir}/dist
    python -m twine check {env_tmp_dir}/dist/*

[testenv:migrations]
commands =
    python tests/manage.py check
    python tests/manage.py makemigrations --check --dry-run
    python tests/manage.py migrate --noinput
