/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/author": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API viewset for Author objects. */
        get: operations["author_list"];
        put?: never;
        /** @description API viewset for Author objects. */
        post: operations["author_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/author/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API viewset for Author objects. */
        get: operations["author_retrieve"];
        /** @description API viewset for Author objects. */
        put: operations["author_update"];
        post?: never;
        /** @description API viewset for Author objects. */
        delete: operations["author_destroy"];
        options?: never;
        head?: never;
        /** @description API viewset for Author objects. */
        patch: operations["author_partial_update"];
        trace?: never;
    };
    "/api/v1/contest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API view Contest objects. */
        get: operations["contest_list"];
        put?: never;
        /** @description API view Contest objects. */
        post: operations["contest_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/contest/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API view Contest objects. */
        get: operations["contest_retrieve"];
        /** @description API view Contest objects. */
        put: operations["contest_update"];
        post?: never;
        /** @description API view Contest objects. */
        delete: operations["contest_destroy"];
        options?: never;
        head?: never;
        /** @description API view Contest objects. */
        patch: operations["contest_partial_update"];
        trace?: never;
    };
    "/api/v1/file": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description API viewset for File objects. */
        post: operations["file_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/institution": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List institutions with optional filters. */
        get: operations["institution_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/judge/contest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List contests assigned to the requesting judge. */
        get: operations["judge_contest_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/judge/submission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List paid submissions assigned to an active judge. */
        get: operations["judge_submission_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payment": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API viewset for Payment objects. */
        get: operations["payment_list"];
        put?: never;
        /** @description API viewset for Payment objects. */
        post: operations["payment_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payment/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API viewset for Payment objects. */
        get: operations["payment_retrieve"];
        /** @description API viewset for Payment objects. */
        put: operations["payment_update"];
        post?: never;
        /** @description API viewset for Payment objects. */
        delete: operations["payment_destroy"];
        options?: never;
        head?: never;
        /** @description API viewset for Payment objects. */
        patch: operations["payment_partial_update"];
        trace?: never;
    };
    "/api/v1/rating": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API viewset for Rating objects. */
        get: operations["rating_list"];
        put?: never;
        /** @description API viewset for Rating objects. */
        post: operations["rating_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/rating/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API viewset for Rating objects. */
        get: operations["rating_retrieve"];
        /** @description API viewset for Rating objects. */
        put: operations["rating_update"];
        post?: never;
        /** @description API viewset for Rating objects. */
        delete: operations["rating_destroy"];
        options?: never;
        head?: never;
        /** @description API viewset for Rating objects. */
        patch: operations["rating_partial_update"];
        trace?: never;
    };
    "/api/v1/results/submission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List and retrieve accepted submissions after publication. */
        get: operations["results_submission_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/submission/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List and retrieve accepted submissions after publication. */
        get: operations["results_submission_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/results/theme/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Retrieve published results for a theme. */
        get: operations["results_theme_retrieve"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submission": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API view Submission objects. */
        get: operations["submission_list"];
        put?: never;
        /** @description Create one coherent submission set, atomically, for either payload shape. */
        post: operations["submission_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submission/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description API view Submission objects. */
        get: operations["submission_retrieve"];
        /** @description Serialize file reassignment with other submission writes. */
        put: operations["submission_update"];
        post?: never;
        /** @description Delete an unpublished submission owned by the requester. */
        delete: operations["submission_destroy"];
        options?: never;
        head?: never;
        /** @description API view Submission objects. */
        patch: operations["submission_partial_update"];
        trace?: never;
    };
    "/api/v1/submissionset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List and delete the requesting user's submission sets. */
        get: operations["submissionset_list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/submissionset/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List and delete the requesting user's submission sets. */
        get: operations["submissionset_retrieve"];
        put?: never;
        post?: never;
        /** @description Destroy the instance and all related submissions. */
        delete: operations["submissionset_destroy"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description List accounts visible to the caller. */
        get: operations["user_list"];
        put?: never;
        /** @description Manage the current account, with administrative access for superusers. */
        post: operations["user_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** @description Manage the current account, with administrative access for superusers. */
        get: operations["user_retrieve"];
        /** @description Manage the current account, with administrative access for superusers. */
        put: operations["user_update"];
        post?: never;
        /** @description Manage the current account, with administrative access for superusers. */
        delete: operations["user_destroy"];
        options?: never;
        head?: never;
        /** @description Manage the current account, with administrative access for superusers. */
        patch: operations["user_partial_update"];
        trace?: never;
    };
    "/api/v1/user/{id}/change_password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Change the caller's password and expire previous tokens. */
        post: operations["user_change_password_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/activate_account": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Activate an account using its email token. */
        post: operations["user_activate_account_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Validate credentials and return a token with its expiration. */
        post: operations["user_login_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/password_reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Consume a recovery token and set a new password. */
        post: operations["user_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/user/request_password_reset": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Request an account recovery email. */
        post: operations["user_request_password_reset_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Activate the account referenced by a signed token. */
        ActivationRequest: {
            token: string;
        };
        /** @description Serializer for Author objects. */
        Author: {
            readonly id: number;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
            first_name: string;
            last_name: string;
            /** @description Return author's email for superusers, ``None`` field otherwise. */
            readonly email: string | null;
            /** Format: date */
            dob?: string | null;
            school?: string | null;
            mentor?: string | null;
            club?: string | null;
            distinction?: string | null;
        };
        /** @description Serializer for Author objects. */
        AuthorRequest: {
            first_name: string;
            last_name: string;
            /** Format: date */
            dob?: string | null;
            school?: string | null;
            mentor?: string | null;
            club?: string | null;
            distinction?: string | null;
        };
        /** @description Serializer for Theme objects. */
        AuthorResults: {
            readonly id: number;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
            first_name: string;
            last_name: string;
            /** @description Return author's email for superusers, ``None`` field otherwise. */
            readonly email: string | null;
            /** Format: date */
            dob?: string | null;
            school?: string | null;
            mentor?: string | null;
            club?: string | null;
            distinction?: string | null;
            readonly reward: string | null;
            readonly reward_theme: number | null;
            /** @description Return the optional country supplied by the host user model. */
            readonly country: string | null;
        };
        /** @description Validate a credential change against the current password. */
        ChangePasswordRequest: {
            current_password: string;
            new_password: string;
        };
        /** @description Serializer for Contest objects. */
        Contest: {
            readonly id: number;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
            title: string;
            description?: string | null;
            /** Format: date-time */
            start_date: string;
            /** Format: date-time */
            end_date: string;
            readonly themes: components["schemas"]["Theme"][];
            /** Format: uri */
            header_image?: string | null;
            notice_html?: string;
            confirmation_html?: string;
            dob_required?: boolean;
            club_show?: boolean;
            club_required?: boolean;
            school_show?: boolean;
            school_required?: boolean;
        };
        /** @description Serializer for Contest objects. */
        ContestRequest: {
            title: string;
            description?: string | null;
            /** Format: date-time */
            start_date: string;
            /** Format: date-time */
            end_date: string;
            /** Format: binary */
            header_image?: string | null;
            notice_html?: string;
            confirmation_html?: string;
            dob_required?: boolean;
            club_show?: boolean;
            club_required?: boolean;
            school_show?: boolean;
            school_required?: boolean;
        };
        /** @description Serializer for File objects. */
        File: {
            readonly id: number;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
            /** Format: uri */
            file: string;
            /** Format: uri */
            thumbnail?: string | null;
        };
        /** @description Serializer for File objects. */
        FileRequest: {
            /** Format: binary */
            file: string;
            /** Format: binary */
            thumbnail?: string;
        };
        /** @description Serializer for File objects. */
        IdRelatedRequest: {
            id: number;
        };
        /** @description Serializer for Author objects. */
        Institution: {
            readonly id: number;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
            name: string;
            kind: components["schemas"]["KindEnum"];
        };
        /** @description Serializer for Contest objects. */
        JudgeContest: {
            readonly id: number;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
            title: string;
            description?: string | null;
            /** Format: date-time */
            start_date: string;
            /** Format: date-time */
            end_date: string;
            readonly themes: components["schemas"]["JudgeTheme"][];
            /** Format: uri */
            header_image?: string | null;
            notice_html?: string;
            confirmation_html?: string;
            dob_required?: boolean;
            club_show?: boolean;
            club_required?: boolean;
            school_show?: boolean;
            school_required?: boolean;
        };
        /** @description Serializer for Theme objects. */
        JudgeTheme: {
            readonly id: number;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
            title: string;
            is_series?: boolean;
            /**
             * Number of photos
             * Format: int64
             */
            n_photos: number;
            /** @description Count paid submissions available for judging. */
            readonly submissions_number: number;
            /** @description Count ratings submitted by the requesting judge. */
            readonly ratings_number: number;
        };
        /**
         * @description * `1` - School
         * @enum {integer}
         */
        KindEnum: 1;
        /** @description Authenticate an active account. */
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        PaginatedAuthorList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Author"][];
        };
        PaginatedContestList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Contest"][];
        };
        PaginatedInstitutionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Institution"][];
        };
        PaginatedJudgeContestList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["JudgeContest"][];
        };
        PaginatedPaymentList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Payment"][];
        };
        PaginatedRatingList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Rating"][];
        };
        PaginatedSubmissionList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["Submission"][];
        };
        PaginatedSubmissionResultsList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["SubmissionResults"][];
        };
        PaginatedSubmissionSetList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["SubmissionSet"][];
        };
        PaginatedUserList: {
            /** @example 123 */
            count: number;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=4
             */
            next?: string | null;
            /**
             * Format: uri
             * @example http://api.example.org/accounts/?page=2
             */
            previous?: string | null;
            results: components["schemas"]["User"][];
        };
        /** @description Validate a signed recovery token and replacement password. */
        PasswordResetRequest: {
            token: string;
            new_password: string;
        };
        /** @description Serializer for Author objects. */
        PatchedAuthorRequest: {
            first_name?: string;
            last_name?: string;
            /** Format: date */
            dob?: string | null;
            school?: string | null;
            mentor?: string | null;
            club?: string | null;
            distinction?: string | null;
        };
        /** @description Serializer for Contest objects. */
        PatchedContestRequest: {
            title?: string;
            description?: string | null;
            /** Format: date-time */
            start_date?: string;
            /** Format: date-time */
            end_date?: string;
            /** Format: binary */
            header_image?: string | null;
            notice_html?: string;
            confirmation_html?: string;
            dob_required?: boolean;
            club_show?: boolean;
            club_required?: boolean;
            school_show?: boolean;
            school_required?: boolean;
        };
        /** @description Serializer for Payment objects. */
        PatchedPaymentRequest: {
            submissionset?: number;
            paid?: boolean;
        };
        /** @description Serializer for Rating objects. */
        PatchedRatingRequest: {
            submission?: number;
            /** Format: int64 */
            rating?: number;
        };
        /** @description Serializer for Submission objects. */
        PatchedSubmissionRequest: {
            author?: components["schemas"]["IdRelatedRequest"];
            theme?: number;
            title?: string | null;
            description?: string | null;
            files?: components["schemas"]["IdRelatedRequest"][];
        };
        /** @description Expose a public profile with an embedded postal address. */
        PatchedUserRequest: {
            password?: string;
            /** Format: email */
            email?: string;
            first_name?: string | null;
            last_name?: string | null;
            address?: string | null;
            city?: string | null;
            postal_code?: string | null;
            country?: string | null;
        };
        /** @description Serializer for Payment objects. */
        Payment: {
            readonly id: number;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
            submissionset: number;
            paid?: boolean;
        };
        /** @description Serializer for Payment objects. */
        PaymentRequest: {
            submissionset: number;
            paid?: boolean;
        };
        /** @description Serializer for Rating objects. */
        Rating: {
            readonly id: number;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
            submission: number;
            /** Format: int64 */
            rating: number;
        };
        /** @description Serializer for Rating objects. */
        RatingRequest: {
            submission: number;
            /** Format: int64 */
            rating: number;
        };
        /** @description Request recovery without exposing whether an account exists. */
        RequestPasswordResetRequest: {
            /** Format: email */
            email: string;
        };
        /** @description Serializer for Submission objects. */
        Submission: {
            readonly id: number;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
            author: components["schemas"]["Author"];
            theme: number;
            title?: string | null;
            description?: string | null;
            files: components["schemas"]["File"][];
        };
        /** @description Serializer for Submission objects. */
        SubmissionRequest: {
            author: components["schemas"]["IdRelatedRequest"];
            theme: number;
            title?: string | null;
            description?: string | null;
            files: components["schemas"]["IdRelatedRequest"][];
        };
        /** @description Serialize published submission results and awards. */
        SubmissionResults: {
            readonly id: number;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
            author: components["schemas"]["AuthorResults"];
            theme: number;
            title?: string | null;
            description?: string | null;
            readonly files: components["schemas"]["File"][] | null;
            /** @description Report whether the submission reached the acceptance threshold. */
            readonly accepted: boolean;
            readonly rating: number | null;
            /** @description Return the human-readable award kind when present. */
            readonly reward_kind: string | null;
            readonly reward_label: string | null;
        };
        /** @description Serializer for SubmissionSet objects. */
        SubmissionSet: {
            readonly id: number;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
            submissions: components["schemas"]["Submission"][];
            author: components["schemas"]["Author"];
            contest: number;
        };
        /** @description Serializer for Theme objects. */
        Theme: {
            readonly id: number;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
            title: string;
            is_series?: boolean;
            /**
             * Number of photos
             * Format: int64
             */
            n_photos: number;
            /** @description Count submissions in this theme. */
            readonly submissions_number: number;
        };
        /** @description Serializer for Theme objects. */
        ThemeRequest: {
            title: string;
            is_series?: boolean;
            /**
             * Number of photos
             * Format: int64
             */
            n_photos: number;
        };
        /** @description Serializer for Theme results. */
        ThemeResults: {
            readonly id: number;
            /** Format: date-time */
            readonly created: string;
            /** Format: date-time */
            readonly modified: string;
            title: string;
            is_series?: boolean;
            /**
             * Number of photos
             * Format: int64
             */
            n_photos: number;
            /** @description Count submissions in this theme. */
            readonly submissions_number: number;
            readonly submissions: components["schemas"]["SubmissionResults"][];
        };
        /** @description Represent a newly issued token and its expiration. */
        Token: {
            readonly token: string;
            /** Format: date-time */
            readonly expires: string;
        };
        /** @description Expose a public profile with an embedded postal address. */
        User: {
            /** Format: uuid */
            readonly id: string;
            /** Format: email */
            email: string;
            first_name: string | null;
            last_name: string | null;
            address: string | null;
            city: string | null;
            postal_code: string | null;
            country: string | null;
        };
        /** @description Expose a public profile with an embedded postal address. */
        UserRequest: {
            password: string;
            /** Format: email */
            email: string;
            first_name: string | null;
            last_name: string | null;
            address: string | null;
            city: string | null;
            postal_code: string | null;
            country: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    author_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedAuthorList"];
                };
            };
        };
    };
    author_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthorRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AuthorRequest"];
                "multipart/form-data": components["schemas"]["AuthorRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Author"];
                };
            };
        };
    };
    author_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this author. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Author"];
                };
            };
        };
    };
    author_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this author. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthorRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["AuthorRequest"];
                "multipart/form-data": components["schemas"]["AuthorRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Author"];
                };
            };
        };
    };
    author_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this author. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    author_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this author. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedAuthorRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedAuthorRequest"];
                "multipart/form-data": components["schemas"]["PatchedAuthorRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Author"];
                };
            };
        };
    };
    contest_list: {
        parameters: {
            query?: {
                is_active?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                submitted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedContestList"];
                };
            };
        };
    };
    contest_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ContestRequest"];
                "multipart/form-data": components["schemas"]["ContestRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contest"];
                };
            };
        };
    };
    contest_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this contest. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contest"];
                };
            };
        };
    };
    contest_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this contest. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ContestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ContestRequest"];
                "multipart/form-data": components["schemas"]["ContestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contest"];
                };
            };
        };
    };
    contest_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this contest. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    contest_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this contest. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedContestRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedContestRequest"];
                "multipart/form-data": components["schemas"]["PatchedContestRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contest"];
                };
            };
        };
    };
    file_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "image/jpeg": components["schemas"]["FileRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["File"];
                };
            };
        };
    };
    institution_list: {
        parameters: {
            query?: {
                /** @description * `1` - School */
                kind?: 1;
                name?: string;
                name__contains?: string;
                name__icontains?: string;
                name__iexact?: string;
                name__istartswith?: string;
                name__startswith?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedInstitutionList"];
                };
            };
        };
    };
    judge_contest_list: {
        parameters: {
            query?: {
                is_active?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                submitted?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedJudgeContestList"];
                };
            };
        };
    };
    judge_submission_list: {
        parameters: {
            query?: {
                contest?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                theme?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSubmissionList"];
                };
            };
        };
    };
    payment_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                paid?: boolean;
                submissionset?: number;
                /** @description Multiple values may be separated by commas. */
                submissionset__in?: number[];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedPaymentList"];
                };
            };
        };
    };
    payment_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PaymentRequest"];
                "multipart/form-data": components["schemas"]["PaymentRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
        };
    };
    payment_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this payment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
        };
    };
    payment_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this payment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PaymentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PaymentRequest"];
                "multipart/form-data": components["schemas"]["PaymentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
        };
    };
    payment_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this payment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    payment_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this payment. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedPaymentRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedPaymentRequest"];
                "multipart/form-data": components["schemas"]["PatchedPaymentRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Payment"];
                };
            };
        };
    };
    rating_list: {
        parameters: {
            query?: {
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                submission?: number;
                theme?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedRatingList"];
                };
            };
        };
    };
    rating_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RatingRequest"];
                "multipart/form-data": components["schemas"]["RatingRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rating"];
                };
            };
        };
    };
    rating_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this rating. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rating"];
                };
            };
        };
    };
    rating_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this rating. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RatingRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RatingRequest"];
                "multipart/form-data": components["schemas"]["RatingRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rating"];
                };
            };
        };
    };
    rating_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this rating. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    rating_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this rating. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedRatingRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedRatingRequest"];
                "multipart/form-data": components["schemas"]["PatchedRatingRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Rating"];
                };
            };
        };
    };
    results_submission_list: {
        parameters: {
            query?: {
                contest?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                theme?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSubmissionResultsList"];
                };
            };
        };
    };
    results_submission_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this submission. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionResults"];
                };
            };
        };
    };
    results_theme_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this theme. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ThemeResults"];
                };
            };
        };
    };
    submission_list: {
        parameters: {
            query?: {
                contest?: string;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
                theme?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSubmissionList"];
                };
            };
        };
    };
    submission_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SubmissionRequest"];
                "multipart/form-data": components["schemas"]["SubmissionRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
        };
    };
    submission_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this submission. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
        };
    };
    submission_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this submission. */
                id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmissionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["SubmissionRequest"];
                "multipart/form-data": components["schemas"]["SubmissionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
        };
    };
    submission_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this submission. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    submission_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this submission. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedSubmissionRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedSubmissionRequest"];
                "multipart/form-data": components["schemas"]["PatchedSubmissionRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Submission"];
                };
            };
        };
    };
    submissionset_list: {
        parameters: {
            query?: {
                contest?: number;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedSubmissionSetList"];
                };
            };
        };
    };
    submissionset_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this submission set. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmissionSet"];
                };
            };
        };
    };
    submissionset_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description A unique integer value identifying this submission set. */
                id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    user_list: {
        parameters: {
            query?: {
                current?: boolean;
                /** @description Which field to use when ordering the results. */
                ordering?: string;
                /** @description A page number within the paginated result set. */
                page?: number;
                /** @description Number of results to return per page. */
                page_size?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedUserList"];
                };
            };
        };
    };
    user_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRequest"];
                "multipart/form-data": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    user_retrieve: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    user_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["UserRequest"];
                "multipart/form-data": components["schemas"]["UserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    user_destroy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No response body */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    user_partial_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["PatchedUserRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PatchedUserRequest"];
                "multipart/form-data": components["schemas"]["PatchedUserRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    user_change_password_create: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ChangePasswordRequest"];
                "multipart/form-data": components["schemas"]["ChangePasswordRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    user_activate_account_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ActivationRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["ActivationRequest"];
                "multipart/form-data": components["schemas"]["ActivationRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    user_login_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["LoginRequest"];
                "multipart/form-data": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Token"];
                };
            };
        };
    };
    user_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordResetRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["PasswordResetRequest"];
                "multipart/form-data": components["schemas"]["PasswordResetRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    user_request_password_reset_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RequestPasswordResetRequest"];
                "application/x-www-form-urlencoded": components["schemas"]["RequestPasswordResetRequest"];
                "multipart/form-data": components["schemas"]["RequestPasswordResetRequest"];
            };
        };
        responses: {
            /** @description No response body */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
