# Generated by Django 3.0rc1 on 2020-03-14 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drf_user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('internal_id',)},
        ),
    ]
